# build environment
FROM node:12.18.0-alpine as build
WORKDIR /app
COPY client/package.json ./
COPY client/package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY client ./
RUN npm run build

# serve environment
FROM nginx:stable-alpine
COPY client/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 50102
CMD ["nginx", "-g", "daemon off;"]